"""Give guardrail policy revisions database-owned precedence."""

from __future__ import annotations

from alembic import op

revision = "029"
down_revision = "028"
branch_labels = None
depends_on = None

_COLUMNS = """
    tenant_id, revision_id, scope_type, deployment_ref,
    policy_json, changed_by, created_at
"""


def _create_ordered_table() -> None:
    order_column = (
        "revision_order BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if op.get_bind().dialect.name == "postgresql"
        else "revision_order INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    op.execute(f"""CREATE TABLE guardrail_policy_revisions (
        {order_column},
        tenant_id TEXT NOT NULL,
        revision_id TEXT NOT NULL,
        scope_type TEXT NOT NULL CHECK (scope_type IN ('tenant', 'deployment')),
        deployment_ref TEXT NOT NULL DEFAULT '',
        policy_json TEXT NOT NULL,
        changed_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (tenant_id, revision_id))""")


def _create_legacy_table() -> None:
    op.execute("""CREATE TABLE guardrail_policy_revisions (
        tenant_id TEXT NOT NULL,
        revision_id TEXT NOT NULL,
        scope_type TEXT NOT NULL CHECK (scope_type IN ('tenant', 'deployment')),
        deployment_ref TEXT NOT NULL DEFAULT '',
        policy_json TEXT NOT NULL,
        changed_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        PRIMARY KEY (tenant_id, revision_id))""")


def _create_lookup_index() -> None:
    op.execute("""CREATE INDEX idx_guardrail_policy_lookup
        ON guardrail_policy_revisions
        (tenant_id, scope_type, deployment_ref, revision_order)""")


def upgrade() -> None:
    bind = op.get_bind()
    op.execute("ALTER TABLE guardrail_policy_revisions RENAME TO guardrail_policy_revisions_legacy")
    op.execute("DROP INDEX idx_guardrail_policy_lookup")
    if bind.dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE guardrail_policy_revisions_legacy "
            "RENAME CONSTRAINT guardrail_policy_revisions_pkey "
            "TO guardrail_policy_revisions_legacy_pkey"
        )
    _create_ordered_table()
    op.execute(f"""INSERT INTO guardrail_policy_revisions
        (revision_order, {_COLUMNS})
        SELECT ROW_NUMBER() OVER (ORDER BY tenant_id, created_at, revision_id), {_COLUMNS}
        FROM guardrail_policy_revisions_legacy""")
    op.execute("DROP TABLE guardrail_policy_revisions_legacy")
    if bind.dialect.name == "postgresql":
        op.execute("""SELECT setval(
            pg_get_serial_sequence('guardrail_policy_revisions', 'revision_order'),
            COALESCE((SELECT MAX(revision_order) FROM guardrail_policy_revisions), 1),
            EXISTS (SELECT 1 FROM guardrail_policy_revisions))""")
    _create_lookup_index()


def downgrade() -> None:
    bind = op.get_bind()
    op.execute(
        "ALTER TABLE guardrail_policy_revisions RENAME TO guardrail_policy_revisions_ordered"
    )
    op.execute("DROP INDEX idx_guardrail_policy_lookup")
    if bind.dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE guardrail_policy_revisions_ordered "
            "RENAME CONSTRAINT guardrail_policy_revisions_pkey "
            "TO guardrail_policy_revisions_ordered_pkey"
        )
    _create_legacy_table()
    op.execute(f"""INSERT INTO guardrail_policy_revisions ({_COLUMNS})
        SELECT {_COLUMNS} FROM guardrail_policy_revisions_ordered ORDER BY revision_order""")
    op.execute("DROP TABLE guardrail_policy_revisions_ordered")
    op.execute("""CREATE INDEX idx_guardrail_policy_lookup
        ON guardrail_policy_revisions
        (tenant_id, scope_type, deployment_ref, created_at, revision_id)""")
