/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/studio/v1/node-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Node Types
         * @description Return all available node types with their port definitions.
         */
        get: operations["list_node_types_api_studio_v1_node_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflows
         * @description List all workflows as summaries.
         */
        get: operations["list_workflows_api_studio_v1_workflows_get"];
        put?: never;
        /**
         * Create Workflow
         * @description Create a new workflow with default Studio metadata.
         */
        post: operations["create_workflow_api_studio_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow
         * @description Get a workflow with full detail including nodes, edges, and viewport.
         */
        get: operations["get_workflow_api_studio_v1_workflows__workflow_id__get"];
        /**
         * Update Workflow
         * @description Update a workflow's name, structure (nodes/edges), and visual layout.
         *
         *     Only draft graphs are editable — published versions are immutable; clone one
         *     to a draft first (POST .../clone). When ``nodes`` are supplied they are built
         *     into real executable graph nodes (and ``edges`` into graph edges), so the
         *     canvas authors the actual graph, not just visual metadata.
         */
        put: operations["update_workflow_api_studio_v1_workflows__workflow_id__put"];
        post?: never;
        /**
         * Delete Workflow
         * @description Archive a workflow (soft delete).
         */
        delete: operations["delete_workflow_api_studio_v1_workflows__workflow_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/v1/workflows/{workflow_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone Workflow
         * @description Clone a published workflow into a new editable draft version.
         */
        post: operations["clone_workflow_api_studio_v1_workflows__workflow_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Runs */
        get: operations["list_admin_runs_v1_admin_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_v1_admin_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runs/{run_id}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interrupt Run
         * @description Interrupt a running run (transitions to WAITING_INTERRUPT).
         */
        post: operations["interrupt_run_v1_admin_runs__run_id__interrupt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runs/{run_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Run
         * @description Replay a dead-letter or failed run by resetting it to PENDING.
         */
        post: operations["replay_run_v1_admin_runs__run_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Deployments
         * @description All persisted deployment versions, newest first.
         *
         *     ``serving`` marks the deployment version this service instance was
         *     bootstrapped with (the one /health reports).
         */
        get: operations["list_deployments_v1_deployments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_v1_deployments__deployment_ref__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_v1_deployments__deployment_ref__approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/approvals/{approval_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Approval */
        post: operations["resolve_approval_v1_deployments__deployment_ref__approvals__approval_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/attestation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attestation */
        get: operations["get_attestation_v1_deployments__deployment_ref__attestation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audits */
        get: operations["list_audits_v1_deployments__deployment_ref__audits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deployment Cost
         * @description Return cumulative spend for a deployment (per D-15, D-16).
         */
        get: operations["get_deployment_cost_v1_deployments__deployment_ref__cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deployment Evidence */
        get: operations["get_deployment_evidence_v1_deployments__deployment_ref__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/input-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Input Contract */
        get: operations["get_input_contract_v1_deployments__deployment_ref__input_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deployment Metadata */
        get: operations["get_deployment_metadata_v1_deployments__deployment_ref__metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/output-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Output Contract */
        get: operations["get_output_contract_v1_deployments__deployment_ref__output_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/result-error-state-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result Error State Schema */
        get: operations["get_result_error_state_schema_v1_deployments__deployment_ref__result_error_state_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deployment Timeline */
        get: operations["get_deployment_timeline_v1_deployments__deployment_ref__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployments/{deployment_ref}/verify-attestation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Verify Attestation */
        post: operations["post_verify_attestation_v1_deployments__deployment_ref__verify_attestation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Evidence */
        get: operations["get_run_evidence_v1_runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Timeline */
        get: operations["get_run_timeline_v1_runs__run_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_v1_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_v1_templates__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{name}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_v1_templates__name___version__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/{tenant_id}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tenant Cost
         * @description Return cumulative spend for a tenant (per D-14, D-16).
         */
        get: operations["get_tenant_cost_v1_tenants__tenant_id__cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dead Letters */
        get: operations["list_dead_letters_v1_webhooks_dead_letters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/dead-letters/{dead_letter_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay Dead Letter */
        post: operations["replay_dead_letter_v1_webhooks_dead_letters__dead_letter_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscriptions */
        get: operations["list_subscriptions_v1_webhooks_subscriptions_get"];
        put?: never;
        /** Create Subscription */
        post: operations["create_subscription_v1_webhooks_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscription */
        get: operations["get_subscription_v1_webhooks_subscriptions__subscription_id__get"];
        put?: never;
        post?: never;
        /** Deactivate Subscription */
        delete: operations["deactivate_subscription_v1_webhooks_subscriptions__subscription_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorIdentity
         * @description Stable actor identity recorded on runs, approvals, and audits.
         */
        ActorIdentity: {
            auth_method: components["schemas"]["AuthMethod"];
            /** Roles */
            roles?: components["schemas"]["ServiceRole"][];
            /** Subject */
            subject: string;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /**
         * AdminRunListResponse
         * @description Response for the admin run list endpoint.
         */
        AdminRunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunStatusResponse"][];
            /** Total */
            total: number;
        };
        /**
         * ApprovalActionRecord
         * @description A record of an approval-related action (e.g. requested, approved, denied).
         *
         *     Used when a node requires human or system approval before proceeding.
         *     Tracks who took the action and when it happened.
         */
        ApprovalActionRecord: {
            /** Action */
            action: string;
            actor?: components["schemas"]["ActorIdentity"] | null;
            /** Approval Id */
            approval_id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /**
         * ApprovalDecision
         * @description The possible choices a human reviewer can make on an approval request.
         *
         *     APPROVE — accept as-is. REJECT — deny the action. EDIT_AND_APPROVE — modify
         *     the proposed payload and then accept it.
         * @enum {string}
         */
        ApprovalDecision: "approve" | "reject" | "edit_and_approve";
        /**
         * ApprovalPausedState
         * @description Public state for a run paused on human approval.
         */
        ApprovalPausedState: {
            /** Approval Id */
            approval_id?: string | null;
            /** Input Payload */
            input_payload?: {
                [key: string]: unknown;
            };
            /** Node Id */
            node_id: string;
        };
        /**
         * ApprovalRecord
         * @description The main approval object that tracks a single approval request.
         *
         *     Created when an agent workflow hits a node that requires human sign-off.
         *     Contains everything a reviewer needs: a summary, rationale, the proposed
         *     payload, which actions are allowed, and (once answered) the resolution.
         */
        ApprovalRecord: {
            /** Allowed Actions */
            allowed_actions?: components["schemas"]["ApprovalDecision"][];
            /** Approval Id */
            approval_id?: string;
            /** Context Excerpt */
            context_excerpt?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Deployment Ref */
            deployment_ref: string;
            /** Escalated From Id */
            escalated_from_id?: string | null;
            /** Escalation Action */
            escalation_action?: string | null;
            /** Graph Version Ref */
            graph_version_ref: string;
            /** @default approval */
            interaction_type: components["schemas"]["HumanInteractionType"];
            /** Node Id */
            node_id: string;
            /** Proposed Payload */
            proposed_payload?: {
                [key: string]: unknown;
            } | null;
            /** Rationale */
            rationale: string;
            requested_by?: components["schemas"]["ActorIdentity"] | null;
            /** @default approve */
            requested_decision: components["schemas"]["ApprovalDecision"];
            resolution?: components["schemas"]["ApprovalResolution"] | null;
            /** Resolution Schema Ref */
            resolution_schema_ref?: string | null;
            /** Run Id */
            run_id: string;
            /** Sla Deadline */
            sla_deadline?: string | null;
            /** @default pending */
            status: components["schemas"]["ApprovalStatus"];
            /** Summary */
            summary: string;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Thread Id */
            thread_id?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Urgency Metadata */
            urgency_metadata?: {
                [key: string]: unknown;
            };
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /**
         * ApprovalResolution
         * @description Holds the details of how an approval was resolved.
         *
         *     Stores who made the decision, what they decided, any edits they made to
         *     the payload, and when the decision happened.
         */
        ApprovalResolution: {
            actor: components["schemas"]["ActorIdentity"];
            decision: components["schemas"]["ApprovalDecision"];
            /** Edited Payload */
            edited_payload?: {
                [key: string]: unknown;
            } | null;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at?: string;
        };
        /**
         * ApprovalResolutionRequest
         * @description Request body for resolving a pending approval.
         */
        ApprovalResolutionRequest: {
            decision: components["schemas"]["ApprovalDecision"];
            /** Edited Payload */
            edited_payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ApprovalResolutionResponse
         * @description Response body returned after resolving an approval.
         */
        ApprovalResolutionResponse: {
            approval: components["schemas"]["ApprovalRecord"];
            run: components["schemas"]["RunStatusResponse"];
        };
        /**
         * ApprovalStatus
         * @description Whether an approval request is still waiting or has been answered.
         *
         *     PENDING means no decision yet; RESOLVED means a human has responded.
         * @enum {string}
         */
        ApprovalStatus: "pending" | "resolved" | "escalated";
        /**
         * AttestationVerificationResponse
         * @description Verification result for a supplied deployment attestation.
         */
        AttestationVerificationResponse: {
            /** Mismatches */
            mismatches?: string[];
            /** Verified */
            verified: boolean;
        };
        /**
         * AuditRecordListResponse
         * @description Public response for deployment-scoped audit lookups.
         */
        AuditRecordListResponse: {
            /** Deployment Ref */
            deployment_ref: string;
            /** Records */
            records?: components["schemas"]["NodeAuditRecord"][];
        };
        /**
         * AuditTimelineResponse
         * @description Public response for ordered audit timelines.
         */
        AuditTimelineResponse: {
            /** Deployment Ref */
            deployment_ref: string;
            /** Entries */
            entries?: components["schemas"]["NodeAuditRecord"][];
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * AuthMethod
         * @description Supported request authentication methods.
         * @enum {string}
         */
        AuthMethod: "api_key" | "bearer";
        /**
         * CreateSubscriptionRequest
         * @description Request body for creating a webhook subscription.
         */
        CreateSubscriptionRequest: {
            /** Deployment Ref */
            deployment_ref: string;
            /** Event Types */
            event_types: string[];
            /** Target Url */
            target_url: string;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
        };
        /**
         * CreateTemplateRequest
         * @description Request body for creating a new template.
         */
        CreateTemplateRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Template Str */
            template_str: string;
            /**
             * Variables
             * @default []
             */
            variables: string[];
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /**
         * CreateWorkflowRequest
         * @description Request body for creating a new workflow.
         */
        CreateWorkflowRequest: {
            /** Name */
            name: string;
        };
        /**
         * DependencyStatus
         * @description Status of a single dependency check.
         */
        DependencyStatus: {
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Status */
            status: string;
        };
        /**
         * DeploymentAttestationResponse
         * @description Stable attestation payload for a deployment snapshot.
         */
        DeploymentAttestationResponse: {
            /** Attestation Digest */
            attestation_digest: string;
            /** Contract Snapshot Digest */
            contract_snapshot_digest: string;
            /** Created At */
            created_at: string;
            /** Deployment Ref */
            deployment_ref: string;
            /** Deployment Version */
            deployment_version: number;
            /** Entry Input Contract Ref */
            entry_input_contract_ref?: string | null;
            /** Entry Input Contract Version */
            entry_input_contract_version?: number | null;
            /** Entry Output Contract Ref */
            entry_output_contract_ref?: string | null;
            /** Entry Output Contract Version */
            entry_output_contract_version?: number | null;
            /** Graph Id */
            graph_id: string;
            /** Graph Snapshot Digest */
            graph_snapshot_digest: string;
            /** Graph Version */
            graph_version: number;
            /** Graph Version Ref */
            graph_version_ref: string;
            /** Settings Snapshot Digest */
            settings_snapshot_digest: string;
        };
        /**
         * DeploymentCostResponse
         * @description Response for GET /v1/deployments/{deployment_ref}/cost (per D-15).
         */
        DeploymentCostResponse: {
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Deployment Ref */
            deployment_ref: string;
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /**
         * DeploymentEvidenceResponse
         * @description Review-friendly evidence bundle for a deployment snapshot.
         */
        DeploymentEvidenceResponse: {
            /** Approvals */
            approvals?: components["schemas"]["ApprovalRecord"][];
            /** Audits */
            audits?: components["schemas"]["NodeAuditRecord"][];
            deployment: components["schemas"]["DeploymentVersionMetadataResponse"];
            /** Policy Events */
            policy_events?: string[];
            /** Run Ids */
            run_ids?: string[];
            summary: components["schemas"]["EvidenceSummaryResponse"];
        };
        /**
         * DeploymentResultErrorStateSchemaResponse
         * @description Combined terminal result and error schema for a deployed version.
         */
        DeploymentResultErrorStateSchemaResponse: {
            /** Deployment Ref */
            deployment_ref: string;
            /** Deployment Version */
            deployment_version: number;
            /** Error State Schema */
            error_state_schema?: {
                [key: string]: unknown;
            };
            /** Graph Version Ref */
            graph_version_ref: string;
            result_contract: components["schemas"]["PublicContractSchemaResponse"];
            /** Result State Schema */
            result_state_schema?: {
                [key: string]: unknown;
            };
        };
        /**
         * DeploymentStatus
         * @description Lifecycle status for immutable deployment versions.
         * @enum {string}
         */
        DeploymentStatus: "active" | "superseded";
        /**
         * DeploymentSummaryResponse
         * @description One persisted deployment version, as shown in the console.
         */
        DeploymentSummaryResponse: {
            /** Created At */
            created_at: string;
            /** Deployment Ref */
            deployment_ref: string;
            /** Graph Version Ref */
            graph_version_ref: string;
            /** Serving */
            serving: boolean;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /**
         * DeploymentVersionMetadataResponse
         * @description Public metadata for one deployed version.
         */
        DeploymentVersionMetadataResponse: {
            /** Attestation Ref */
            attestation_ref?: string | null;
            /** Audit Ref */
            audit_ref?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deployment Ref */
            deployment_ref: string;
            /** Deployment Settings Snapshot */
            deployment_settings_snapshot?: {
                [key: string]: unknown;
            };
            /** Deployment Version */
            deployment_version: number;
            /** Entry Input Contract Ref */
            entry_input_contract_ref?: string | null;
            /** Entry Input Contract Version */
            entry_input_contract_version?: number | null;
            /** Entry Output Contract Ref */
            entry_output_contract_ref?: string | null;
            /** Entry Output Contract Version */
            entry_output_contract_version?: number | null;
            /** Evidence Ref */
            evidence_ref?: string | null;
            /** Graph Id */
            graph_id: string;
            /** Graph Version */
            graph_version: number;
            /** Graph Version Ref */
            graph_version_ref: string;
            status: components["schemas"]["DeploymentStatus"];
            /** Timeline Ref */
            timeline_ref?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EvidenceSummaryResponse
         * @description Aggregated governance counts for an evidence bundle.
         */
        EvidenceSummaryResponse: {
            /**
             * Approval Count
             * @default 0
             */
            approval_count: number;
            /**
             * Audit Count
             * @default 0
             */
            audit_count: number;
            /**
             * Memory Interaction Count
             * @default 0
             */
            memory_interaction_count: number;
            /**
             * Tool Call Count
             * @default 0
             */
            tool_call_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response payload for the wrapper health endpoint.
         */
        HealthResponse: {
            /** Deployment Ref */
            deployment_ref: string;
            /** Deployment Version */
            deployment_version: number;
            /** Graph Version Ref */
            graph_version_ref: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * HumanInteractionType
         * @description The kind of interaction the system is requesting from a human.
         *
         *     For example, "approval" means the system needs a yes/no decision,
         *     while "clarification" means it needs more information to proceed.
         * @enum {string}
         */
        HumanInteractionType: "approval" | "clarification" | "request_input" | "notification";
        /**
         * LivenessResponse
         * @description Response payload for the liveness probe.
         */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * MemoryAccessRecord
         * @description A record of a single memory read or write during a node execution.
         *
         *     Tracks which memory store was accessed, what operation was performed
         *     (e.g. read, write, delete), and the key/value involved.
         */
        MemoryAccessRecord: {
            /** Connector Type */
            connector_type: string;
            /** Key */
            key: string;
            /** Memory Ref */
            memory_ref: string;
            /** Operation */
            operation: string;
            /** Scope */
            scope: string;
            /** Value */
            value?: unknown | null;
        };
        /**
         * NodeAuditRecord
         * @description The main audit record for a single node execution.
         *
         *     This is the core audit object. It captures everything that happened
         *     when a node ran: inputs, outputs, tool calls, memory accesses,
         *     approval actions, validation results, timing, and any errors.
         */
        NodeAuditRecord: {
            actor?: components["schemas"]["ActorIdentity"] | null;
            /** Approval Actions */
            approval_actions?: components["schemas"]["ApprovalActionRecord"][];
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /** Audit Id */
            audit_id: string;
            /** Completed At */
            completed_at?: string | null;
            /** Condition Results */
            condition_results?: {
                [key: string]: unknown;
            }[];
            /** Cost Event Id */
            cost_event_id?: string | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Deployment Ref */
            deployment_ref: string;
            /** Error */
            error?: string | null;
            /** Execution Metadata */
            execution_metadata?: {
                [key: string]: unknown;
            };
            /** Graph Version Ref */
            graph_version_ref: string;
            /** Input Snapshot */
            input_snapshot?: {
                [key: string]: unknown;
            };
            /** Memory Interactions */
            memory_interactions?: components["schemas"]["MemoryAccessRecord"][];
            /** Node Id */
            node_id: string;
            /**
             * Node Version
             * @default 1
             */
            node_version: number;
            /** Output Snapshot */
            output_snapshot?: {
                [key: string]: unknown;
            };
            /** Previous Record Digest */
            previous_record_digest?: string | null;
            /** Record Digest */
            record_digest?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Status */
            status: string;
            /** Stderr */
            stderr?: string | null;
            /** Stdout */
            stdout?: string | null;
            /** Supersedes Audit Id */
            supersedes_audit_id?: string | null;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Thread Id */
            thread_id?: string | null;
            token_usage?: components["schemas"]["TokenUsage"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRecord"][];
            /** Validation Results */
            validation_results?: {
                [key: string]: unknown;
            };
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /**
         * NodeTypeResponse
         * @description A node type available in the Studio palette.
         */
        NodeTypeResponse: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Ports */
            ports: components["schemas"]["PortDefinitionResponse"][];
            /** Type */
            type: string;
        };
        /**
         * PortDefinitionResponse
         * @description A port on a node type.
         */
        PortDefinitionResponse: {
            /** Direction */
            direction: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
        };
        /**
         * PublicContractSchemaResponse
         * @description Public contract payload exposed by the deployment API.
         */
        PublicContractSchemaResponse: {
            /** Json Schema */
            json_schema?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /**
         * ReadinessResponse
         * @description Response payload for the readiness probe.
         */
        ReadinessResponse: {
            /** Checks */
            checks?: {
                [key: string]: components["schemas"]["DependencyStatus"];
            };
            /** Status */
            status: string;
        };
        /**
         * RunEvidenceResponse
         * @description Review-friendly evidence bundle for a single run.
         */
        RunEvidenceResponse: {
            /** Approvals */
            approvals?: components["schemas"]["ApprovalRecord"][];
            /** Audits */
            audits?: components["schemas"]["NodeAuditRecord"][];
            /** Policy Events */
            policy_events?: string[];
            run: components["schemas"]["RunStatusResponse"];
            summary: components["schemas"]["EvidenceSummaryResponse"];
        };
        /**
         * RunFailureState
         * @description Details about why a run failed.
         *
         *     When a run ends in an error, this stores the reason and any extra details
         *     so you can figure out what went wrong.
         */
        RunFailureState: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message?: string | null;
            /** Reason */
            reason: string;
        };
        /**
         * RunInvocationRequest
         * @description Request body for creating a new run.
         */
        RunInvocationRequest: {
            /** Input Payload */
            input_payload?: {
                [key: string]: unknown;
            };
            /** Thread Id */
            thread_id?: string | null;
        };
        /**
         * RunInvocationResponse
         * @description Response body for run creation.
         */
        RunInvocationResponse: {
            approval_paused_state?: components["schemas"]["ApprovalPausedState"] | null;
            /** Audit Refs */
            audit_refs?: string[];
            /** Current Step */
            current_step?: string | null;
            /** Deployment Ref */
            deployment_ref: string;
            /** Evidence Ref */
            evidence_ref?: string | null;
            failure_state?: components["schemas"]["RunFailureState"] | null;
            /** Graph Version Ref */
            graph_version_ref: string;
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunPublicStatus"];
            submitted_by?: components["schemas"]["ActorIdentity"] | null;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Terminal Output */
            terminal_output?: unknown | null;
            /** Thread Id */
            thread_id: string;
            /** Timeline Ref */
            timeline_ref?: string | null;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /**
         * RunPublicStatus
         * @description Public run lifecycle states returned by the HTTP API.
         * @enum {string}
         */
        RunPublicStatus: "queued" | "running" | "paused_for_approval" | "waiting_interrupt" | "succeeded" | "failed" | "terminated_by_policy" | "terminated_by_loop_guard" | "dead_letter";
        /**
         * RunStatusResponse
         * @description Public serialization of run state.
         */
        RunStatusResponse: {
            approval_paused_state?: components["schemas"]["ApprovalPausedState"] | null;
            /** Audit Refs */
            audit_refs?: string[];
            /** Current Step */
            current_step?: string | null;
            /** Deployment Ref */
            deployment_ref: string;
            /** Evidence Ref */
            evidence_ref?: string | null;
            failure_state?: components["schemas"]["RunFailureState"] | null;
            /** Graph Version Ref */
            graph_version_ref: string;
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunPublicStatus"];
            submitted_by?: components["schemas"]["ActorIdentity"] | null;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Terminal Output */
            terminal_output?: unknown | null;
            /** Thread Id */
            thread_id: string;
            /** Timeline Ref */
            timeline_ref?: string | null;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /**
         * ServiceRole
         * @description Service roles used by route authorization.
         * @enum {string}
         */
        ServiceRole: "operator" | "reviewer" | "admin";
        /**
         * StudioEdgeResponse
         * @description An edge as represented in the Studio frontend.
         */
        StudioEdgeResponse: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Source Handle */
            source_handle?: string | null;
            /** Target */
            target: string;
            /** Target Handle */
            target_handle?: string | null;
        };
        /**
         * StudioNodeResponse
         * @description A node as represented in the Studio frontend.
         */
        StudioNodeResponse: {
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            position: components["schemas"]["StudioPosition"];
            /** Type */
            type: string;
        };
        /**
         * StudioPosition
         * @description Canvas position for a node in the Studio editor.
         */
        StudioPosition: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /**
         * StudioViewport
         * @description Viewport state for the Studio canvas.
         */
        StudioViewport: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Zoom
             * @default 1
             */
            zoom: number;
        };
        /**
         * TemplateListResponse
         * @description Response for listing templates.
         */
        TemplateListResponse: {
            /** Templates */
            templates: components["schemas"]["TemplateResponse"][];
        };
        /**
         * TemplateResponse
         * @description Response for a single template.
         */
        TemplateResponse: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Template Str */
            template_str: string;
            /** Variables */
            variables: string[];
            /** Version */
            version: number;
        };
        /**
         * TenantCostResponse
         * @description Response for GET /v1/tenants/{tenant_id}/cost (per D-14).
         */
        TenantCostResponse: {
            /** Budget Cap Usd */
            budget_cap_usd?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Tenant Id */
            tenant_id: string;
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /**
         * TokenUsage
         * @description Token consumption metrics from a single LLM provider call.
         *
         *     Tracks input (prompt) tokens, output (completion) tokens, total tokens,
         *     and the model that produced them. Used by ProviderResponse and
         *     NodeAuditRecord for cost attribution and budget enforcement.
         */
        TokenUsage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Model Name
             * @default
             */
            model_name: string;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /**
         * ToolCallRecord
         * @description A record of a single tool call made during a node execution.
         *
         *     Captures which tool was called, what arguments were passed in,
         *     what the tool returned, and whether it produced an error.
         */
        ToolCallRecord: {
            /** Alias */
            alias: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
            /** Outcome */
            outcome?: {
                [key: string]: unknown;
            } | null;
            /** Tool Ref */
            tool_ref: string;
        };
        /**
         * UpdateWorkflowRequest
         * @description Request body for updating an existing workflow.
         */
        UpdateWorkflowRequest: {
            /** Edges */
            edges?: components["schemas"]["StudioEdgeResponse"][] | null;
            /** Name */
            name?: string | null;
            /** Nodes */
            nodes?: components["schemas"]["StudioNodeResponse"][] | null;
            viewport?: components["schemas"]["StudioViewport"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebhookDeadLetterListResponse
         * @description Response for listing dead-letter entries.
         */
        WebhookDeadLetterListResponse: {
            /** Dead Letters */
            dead_letters: components["schemas"]["WebhookDeadLetterResponse"][];
            /** Total */
            total: number;
        };
        /**
         * WebhookDeadLetterResponse
         * @description Response for a single dead-letter entry.
         */
        WebhookDeadLetterResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Created At */
            created_at: string;
            /** Dead Letter Id */
            dead_letter_id: string;
            /** Dead Lettered At */
            dead_lettered_at: string;
            /** Delivery Id */
            delivery_id: string;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Last Error */
            last_error: string | null;
            /** Last Status Code */
            last_status_code: number | null;
            /** Subscription Id */
            subscription_id: string;
        };
        /**
         * WebhookSubscriptionListResponse
         * @description Response for listing webhook subscriptions.
         */
        WebhookSubscriptionListResponse: {
            /** Subscriptions */
            subscriptions: components["schemas"]["WebhookSubscriptionResponse"][];
            /** Total */
            total: number;
        };
        /**
         * WebhookSubscriptionResponse
         * @description Response for a single webhook subscription.
         */
        WebhookSubscriptionResponse: {
            /** Active */
            active: boolean;
            /** Created At */
            created_at: string;
            /** Deployment Ref */
            deployment_ref: string;
            /** Event Types */
            event_types: string[];
            /** Secret */
            secret: string;
            /** Subscription Id */
            subscription_id: string;
            /** Target Url */
            target_url: string;
            /** Tenant Id */
            tenant_id: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * WorkflowDetailResponse
         * @description Full workflow representation with nodes, edges, and viewport.
         */
        WorkflowDetailResponse: {
            /** Edges */
            edges: components["schemas"]["StudioEdgeResponse"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Nodes */
            nodes: components["schemas"]["StudioNodeResponse"][];
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
            /** Version */
            version: number;
            viewport: components["schemas"]["StudioViewport"];
        };
        /**
         * WorkflowSummaryResponse
         * @description Compact workflow representation for list views.
         */
        WorkflowSummaryResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_node_types_api_studio_v1_node_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTypeResponse"][];
                };
            };
        };
    };
    list_workflows_api_studio_v1_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSummaryResponse"][];
                };
            };
        };
    };
    create_workflow_api_studio_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_studio_v1_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workflow_api_studio_v1_workflows__workflow_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workflow_api_studio_v1_workflows__workflow_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_workflow_api_studio_v1_workflows__workflow_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_admin_runs_v1_admin_runs_get: {
        parameters: {
            query?: {
                status_filter?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_v1_admin_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interrupt_run_v1_admin_runs__run_id__interrupt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_run_v1_admin_runs__run_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deployments_v1_deployments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentSummaryResponse"][];
                };
            };
        };
    };
    list_approvals_v1_deployments__deployment_ref__approvals_get: {
        parameters: {
            query?: {
                approval_id?: string | null;
                run_id?: string | null;
                thread_id?: string | null;
            };
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_v1_deployments__deployment_ref__approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_approval_v1_deployments__deployment_ref__approvals__approval_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalResolutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResolutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attestation_v1_deployments__deployment_ref__attestation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentAttestationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audits_v1_deployments__deployment_ref__audits_get: {
        parameters: {
            query?: {
                run_id?: string | null;
                thread_id?: string | null;
                node_id?: string | null;
                graph_version_ref?: string | null;
            };
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecordListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_cost_v1_deployments__deployment_ref__cost_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentCostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_evidence_v1_deployments__deployment_ref__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_input_contract_v1_deployments__deployment_ref__input_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicContractSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_metadata_v1_deployments__deployment_ref__metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentVersionMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_output_contract_v1_deployments__deployment_ref__output_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicContractSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_error_state_schema_v1_deployments__deployment_ref__result_error_state_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentResultErrorStateSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_timeline_v1_deployments__deployment_ref__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_verify_attestation_v1_deployments__deployment_ref__verify_attestation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentAttestationResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationVerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunInvocationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInvocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_evidence_v1_runs__run_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_timeline_v1_runs__run_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_v1_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
        };
    };
    create_template_v1_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_v1_templates__name__get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_v1_templates__name___version__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_cost_v1_tenants__tenant_id__cost_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantCostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dead_letters_v1_webhooks_dead_letters_get: {
        parameters: {
            query?: {
                subscription_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDeadLetterListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_dead_letter_v1_webhooks_dead_letters__dead_letter_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dead_letter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subscriptions_v1_webhooks_subscriptions_get: {
        parameters: {
            query?: {
                deployment_ref?: string | null;
                tenant_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subscription_v1_webhooks_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_v1_webhooks_subscriptions__subscription_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_subscription_v1_webhooks_subscriptions__subscription_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
