"""Dump the zeroth-core OpenAPI spec to JSON for offline consumption.

Produces a reproducible snapshot of the FastAPI OpenAPI document without
requiring a running uvicorn process. The docs CI calls this before
``mkdocs build`` to render the HTTP API reference.

Usage:
    uv run python scripts/dump_openapi.py --out docs/assets/openapi/zeroth-core-openapi.json
    uv run python scripts/dump_openapi.py  # writes to stdout
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def generate_spec_text() -> str:
    """Return the zeroth-core OpenAPI document as canonical JSON text.

    Shared by this script's CLI and the mkdocs build hook
    (``scripts/mkdocs_hooks.py``) so the stub bootstrap below cannot drift
    between the two callers.

    Imports happen inside the function so ``--help`` stays fast and free of
    heavy side effects.

    Importing the service app transitively imports LiteLLM, which by default
    fetches its model cost map over the network at import time. A spec dump --
    and the docs build that now calls this -- must be hermetic, so the local
    backup map is forced first. ``setdefault`` leaves an explicit operator
    setting alone. The cost map does not participate in the OpenAPI schema, so
    this cannot change the generated bytes.

    We construct a FastAPI app directly via ``create_app`` with a minimal stub
    bootstrap. ``create_app`` only reads ``bootstrap.authenticator`` and friends
    at request-time (middleware), so a SimpleNamespace with ``None`` fields is
    sufficient for ``app.openapi()`` -- which is a static schema walk of the
    registered routes. This avoids needing a migrated database, secrets, or any
    runtime wiring.
    """
    import os
    from types import SimpleNamespace

    os.environ.setdefault("LITELLM_LOCAL_MODEL_COST_MAP", "True")

    from zeroth.platform.config.settings import AuthSettings, get_settings
    from zeroth.service.app import create_app

    stub_bootstrap = SimpleNamespace(
        deployment=None,
        graph=None,
        contract_registry=None,
        approval_service=None,
        run_repository=None,
        orchestrator=None,
        audit_repository=None,
        authenticator=None,
        regulus_client=None,
        artifact_store=None,       # Phase 40
        template_registry=None,    # Phase 40
    )
    settings = get_settings()
    original_auth = settings.auth
    try:
        # Offline schema generation has no requests or credential material, but
        # create_app still constructs its signer. Select the explicit
        # development-only path for this bounded operation and restore the
        # caller's settings immediately afterward.
        settings.auth = AuthSettings(
            allow_ephemeral_browser_session_secret_development=True,
        )
        app = create_app(stub_bootstrap)  # type: ignore[arg-type]
    finally:
        settings.auth = original_auth
    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Dump the zeroth-core FastAPI OpenAPI spec to JSON.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output file (default: stdout)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Exit 1 if --out file is missing or differs from freshly generated "
            "spec (drift check for CI)."
        ),
    )
    args = parser.parse_args()

    text = generate_spec_text()

    if args.check:
        if args.out is None:
            sys.stderr.write("--check requires --out\n")
            return 1
        if not args.out.exists():
            sys.stderr.write(f"DRIFT: {args.out} does not exist\n")
            return 1
        existing = args.out.read_text()
        if existing != text:
            sys.stderr.write(
                f"DRIFT: {args.out} is stale. Run "
                f"`python scripts/dump_openapi.py --out {args.out}` to update.\n"
            )
            return 1
        sys.stdout.write(f"OK: {args.out} is up to date.\n")
        return 0

    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
