"""Bounded opt-in CPU samples; code locations only, never locals or arguments."""

import signal
import threading
from collections import Counter


class CPUSampler:
    """Sample the main Python thread per 20ms of process CPU on POSIX.

    Python delivers signal handlers on the main thread, including CPU signals
    generated by other threads. Counts are diagnostic attribution, not precise
    per-function CPU time. Existing signal/timer owners are never replaced.
    """

    def __init__(self):
        self.counts = Counter()
        self.total = 0
        self.dropped = 0
        self.status = "not-started"
        self.previous = None

    def sample(self, _signum, frame):
        frames = []
        while frame is not None and len(frames) < 24:
            code = frame.f_code
            frames.append((code.co_filename, code.co_name, frame.f_lineno))
            frame = frame.f_back
        key = tuple(frames)
        self.total += 1
        if key in self.counts or len(self.counts) < 512:
            self.counts[key] += 1
        else:
            self.dropped += 1

    def __enter__(self):
        if not hasattr(signal, "ITIMER_PROF") or threading.current_thread() is not threading.main_thread():
            self.status = "unsupported"
            return self
        self.previous = signal.getsignal(signal.SIGPROF)
        if self.previous != signal.SIG_DFL or any(signal.getitimer(signal.ITIMER_PROF)):
            self.status = "existing-owner"
            return self
        signal.signal(signal.SIGPROF, self.sample)
        try:
            signal.setitimer(signal.ITIMER_PROF, .02, .02)
        except BaseException:
            signal.signal(signal.SIGPROF, self.previous)
            raise
        self.status = "sampled"
        return self

    def __exit__(self, *_exc):
        if self.status == "sampled":
            signal.setitimer(signal.ITIMER_PROF, 0)
            signal.signal(signal.SIGPROF, self.previous)

    def snapshot(self):
        return {"status": self.status, "total": self.total, "dropped": self.dropped,
                "interval_cpu_ms": 20, "stacks": [
                    {"count": count, "frames": [
                        {"file": file, "function": function, "line": line}
                        for file, function, line in frames]}
                    for frames, count in list(self.counts.items())]}
